// LOOPS ARE USED TO REPEATEDLY EXECUTE SET OF STATEMENTS, THERE ARE THREE DIFFERENT LOOPING STRUCTURE IN C PROGRAMMING

// SYNTAX

// INITIALIZATION 
// WHILE(CONDITION)
// {
//     STATEMENT;
//     INCREMENT OR DECREMENT;
// }